# Generated by Django 4.1 on 2022-11-08 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='data published')),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cashbook_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cashbookapp.cashbook')),
            ],
        ),
        migrations.AddField(
            model_name='cashbook',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='cashbookapp.hashtag'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='post_like',
            field=models.ManyToManyField(blank=True, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
