# Generated by Django 4.1 on 2022-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='추천수')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
        ),
    ]
